#define G4VIS_USE 1

#define G4LIB_BUILD_DLL 1
#define G4UI_USE_QT 1
#define G4UI_USE_TCSH 1
#define G4VIS_USE_OPENGL 1
#define G4VIS_USE_OPENGLQT 1
#define G4VIS_USE_OPENGLX 1
#define G4VIS_USE_QT3D 1
#define QT_3DCORE_LIB 1
#define QT_3DEXTRAS_LIB 
#define G4VIS_BUILD_RAYTRACER_DRIVER 1
#define G4VIS_USE_RAYTRACER 1
#define QT_3DINPUT_LIB 1
#define QT_3DLOGIC_LIB 1
#define QT_3DRENDER_LIB 1
#define QT_CORE_LIB 1
#define QT_GAMEPAD_LIB 1
#define QT_GUI_LIB 1
#define QT_NETWORK_LIB 1
#define QT_NO_DEBUG 1
#define QT_OPENGL_LIB 1
#define QT_PRINTSUPPORT_LIB 
#define G4VIS_USE_VTK 1
// #define G4VIS_USE_VTK_QT 1

#define QT_WIDGETS_LIB

#define GEANT4_BUILD_MULTITHREADED OFF